API_KEY = "your-api-key-here"

LRU_CACHE_MAXSIZE = 1000

APPROVALS_API_RETRIES = 3
APPROVALS_SERVICE_CONCURRENCY_LIMIT = 5  # Renamed from APPROVALS_API_CONCURRENCY_LIMIT
LOG_PROCESSOR_CONCURRENCY_LIMIT = 5
APPROVALS_API_RETRY_DELAY = 1

COINGECKO_API_URL = "https://api.coingecko.com/api/v3/simple/token_price/ethereum"
